### PR TITLE
Updates on the various groupings

### PR DESCRIPTION
**Pull request by wvoigt**
This implements all the grouping choices that are now available.
I don't have a good way to test this.  But I think this is close.

### CODE REVIEW

**Comment by sumpfork** [comment]
Deployed at http://staging.sandflea.org/ - seems ok to me so far, but do test and let me know.

**Comment by wvoigt** [comment]
I'm now seeing some issues.  I need to look at this some more.
1. "Group cards without randomizers separately" is adding cards from expansions that are not selected.  This is probably an issue in main.py that I need to fix.
2. "Group these card types globally", when nothing is selected, is sending an empty list, which then in main.py becomes everything.  This needs to be set to None if nothing is selected.  That is a change here in views.py.
3. I just realized we never added the following to view.py:
- start_decks "Include four start decks with the Base cards."
- curse10 "Package Curse cards into groups of ten cards."
- no_trash "Exclude Trash from cards."

I'll work up the changes to views.py here.   I'm more worried about the expansion exclusion issue for the cards without randomizers.

**Comment by wvoigt** [comment]
So for now, we can leave out group_kingdom.  There is a logic flaw in main.py that I need to work.
And since it would take pulling in a new version of main.py anyway, I think it best to just leave out that option for now.
It can be added back in later when the logic flaw is fixed.

**Comment by wvoigt** [comment]
Can we give this a try now?

**Comment by sumpfork** [comment]
deployed to staging

**Comment by wvoigt** [comment]
This seems to be working as expected without https://github.com/sumpfork/dominiontabs/pull/323
The problem only shows up if:
1. "Group cards without randomizers separately" is checked
2. Not all the expansions are selected
3. The non-selected expansion includes cards that do not have randomizers

In that case, all cards that do not have randomizers will show up in the output in the expansion's "Extra" section.  Even if that expansion is not to be included, and the expansion's cards WITH radomizers do not appear in the output.
The above pull for main.py fixes the issue.

**Comment by sumpfork** [comment]
I think this is all in the new code, though I haven't done extensive testing...

**Pull request closed without merging**
